### ISSUE TITLE
update code for casl 4.x

### ISSUE THREAD

**Issue by twnaing** [stalniy/simple-rails-rest#2]
[related issue](https://github.com/stalniy/casl/issues/214)

> I think the sample should be updated with the followings for `casl` 4.x (at [models/ability.rb:26](https://github.com/stalniy/rails-cancan-api-example/blob/971e716f260814ee8ac345eb16392f30f2d795d9/app/models/ability.rb#L26))
>
> 1. `action` instead of `actions` (not breaking, but `action` is now recommended) 
> 2. `subjectName` insetad of `subject` in (breaking change)
>    a. [blog post](https://medium.com/dailyjs/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec)
>    b. [example](https://github.com/stalniy/casl-vue-api-example)

**Comment by stalniy** [comment]
I updated `action` field but don't know why you decided that `subject` needs to be replaced with `subjectName`
